
<?php
include('br_help.inc');

/*-----------------------------------------*/
/*           Generic translations          */
/*-----------------------------------------*/
/* Initial Screen */
define('Help', 'Ajuda');
define('User', 'Usuario');
define('Logout', 'Sair');
define('Select module', 'Seleciona modulo');
/* Buttons */
define('Search', 'Procurar');

/* Headers */
define('Delete', 'Deletar');
/* Add by JBTorres - 2008 Fev,02           */


/*-----------------------------------------*/
/*             Sales module                */
/*-----------------------------------------*/
define('Sales', 'Vendas');
/* Menu 1 - Sales */
define('New cash sales order', 'Nova ordem de venda em caixa');
define('New sales order', 'Nova ordem de venda');
define('New recurring sales order', 'Nova ordem de venda recorrente');
define('Receipts', 'Recebimentos');
define('Show sales orders', 'Mostra ordens de venda');
define('Sales analysis', 'Analise de Vendas');
/* Screen - New cash sales order */
define('Sales orders', 'Ordens de Vendas');
define('Order no', 'Ordem no');
define('Customer', 'Cliente');
define('Order date', 'Data');
define('Location', 'Local');
define('Receipt', 'Recebido');
define('Not paid', 'Nao pago');
define('Created by', 'Criado por');
define('Product', 'Produto');
define('Comment', 'Comentario');  /* add by JBTorres */
define('Quantity', 'Qtde');
define('Unit price', 'Preco');
define('Amount', 'Saldo');
define('Save', 'Salva');
define('VAT', 'Imposto');
define('To pay', 'A pagar');
define('Payed amount', 'Montante pago');
define('Cancel order', 'Cancela ordem');
define('Show stock moves', 'Mostra estoque em transito');
/* Menu 2 - Customers */
define('Customers', 'Clientes');
/* Screen - Customers */
define('Customer name', 'Nome do cliente');
define('Customer no', 'Cliente No');
define('Name', 'Nome');
define('Balance', 'Saldo');
define('Over due', 'Vencido');
define('New customer', 'Novo cliente');
/* Menu 3 - Period */
define('Period', 'Periodo');
/* Screen - Period */
define('Current period is', 'Periodo atual e');
define('Create recurring receivables', 'Cria recebimento recorrente'); /* What do? add by JBTorres*/
define('Create time debit invoices', 'Cria fatura de debito (time)');  /* What do? add by JBTorres*/
define('Send receivables', 'Envia Recebimentos');  /* What do? add by JBTorres*/



define('Taxable', 'Imposto');
define('Description', 'Descricao');
define('Purchase', 'Compra');
define('Products', 'Produtos');
define('Order id', 'Ordem');
define('New order', 'Nova ordem');
define('Model', 'Modelo');
define('Finish', 'Finaliza');
define('Fullt paid', 'Pagamento Total');
define('Show transaction', 'Mostra transacao');
define('Transactions', 'Transacoes');
define('Narrativ', 'Descricao');
define('Time', 'Data e Hora');
define('Cancel transaction', 'Cancela transacao');
define('New purchase order', 'Novo pedido de compras');
define('Purchase orders', 'Pedido de compra');
define('Suppliers', 'Fornecedores');
define('Supplier balance', 'Balanco do fornecedor');
define('Supplier', 'Fornecedor');
define('Payment', 'Pagamento');
define('Received qty', 'Qtde Recebida');
define('Update', 'Atualiza');
define('Register payable', 'Registra pagamento');
define('Pay', 'Pago');
define('Show payable', 'Mostra pagamento');
define('New payable', 'Novo pagamento');
define('Payables', 'Pagamentos');

define('Categories', 'Categorias');
define('VAT categories', 'Categoria de Impostos');
define('Production orders', 'Ordens de Producao');
define('New production order', 'Nova ordem de producao');
define('Sales price', 'Preco de venda');
define('Purchase price', 'Preco de compra');
define('Fully paid', 'Pagamento total');
define('Invoiced', 'Faturado');
define('Payed', 'Pago');
define('Recurring', 'Recorrente');
define('Invoice', 'Fatura');
define('doInvoice', 'Para faturar');
define('Productno', 'Codigo Produto');
define('Years', 'Anos');
define('Months', 'Meses');





define('Only show', 'Apenas mostra');
define('Unpaid', 'Sem pagto');

define('Rounding', 'Arredondando');
define('Sales order', 'Ordem de vendas');
define('Tabs', 'Tabs');
define('Tab', 'Tab');
define('No of columns', 'No de Colunas');
define('Row', 'Linha');
define('Col', 'Coluna');

define('Exchange', 'Troca');
define('Self-service', 'Self-service');

define('Ordered qty, sales', 'Total (vendas)');
define('Ordered qty, purchase', 'Total (compras)');
define('Add product', 'Novo produto');
define('Prices', 'Precos');
define('Stock', 'Estoque');
define('Save product', 'Grava produto');
define('Units of measure', 'Unidades de medida');
define('Update quantities', 'Atualiza quantidades');
define('Move', 'Move');
define('pieces from', 'itens de');
define('to', 'para');
define('Show stock moves', 'Mostra estoque movido');
define('Starting quantity', 'Saldo inicial');
define('Final quantity', 'Saldo final');

define('Add', 'Adiciona');
define('Amount paid', 'Montante pago');

define('Price lists', 'Listas de preco');
define('Invoice footer', 'Rodape da fatura');
define('Billing period', 'Periodo de faturamento');
define('Accountno', 'No Conta');
define('Revenue', 'Receita');
define('Next', 'Proximo');
define('Registrationno', 'No Registro');
define('Address', 'Endereco');
define('Username', 'Nome Usuario');
define('VAT number', 'No I.E.');
define('Invoice #', 'No Fatura:');
define('Invoice date', 'Data Fatura');
define('Due date', 'Data Atraso');
define('Correction', 'Correcao');
define('Confirm', 'Confirma');
define('Register', 'Registra');
define('Generic transaction', 'Transacao generica');
define('Expense transaction', 'Transacao de despesa');
define('Trip', 'Viagem');
define('Trips', 'Viagens');
define('Distance', 'Distancia');
define('Starttime', 'Inicio');
define('Endtime', 'Termino');
/* Add by JBTorres - 2008 Fev,02           */

/*-----------------------------------------*/
/*           Stock/Inventory module        */
/*-----------------------------------------*/
define('Stock/Inventory', 'Estoque');
/* Add by JBTorres - 2008 Fev,02           */

/*-----------------------------------------*/
/*         Manufactoring module            */
/*-----------------------------------------*/
/* Add by JBTorres - 2008 Fev,02           */
define('Manufacturing', 'Producao');

/*-----------------------------------------*/
/*           Payroll module                */
/*-----------------------------------------*/
define('Payroll', 'Folha');
define('Surname', 'Sobrenome');
define('Show inactive', 'Mostra inativa');


define('Calendar', 'Calendario');
define('New', 'Novo');

define('Employee calendar', 'Calendario do funcionario');
define('Monday', 'Segunda');
define('Tuesday', 'Terca');
define('Wednesday', 'Quarta');
define('Thursday', 'Quinta');
define('Friday', 'Sexta');
define('Saturday', 'Sabado');
define('Sunday', 'Domingo');
define('May', 'Mai');
define('Oct', 'Out');
define('Absence', 'Falta');
define('Attendence', 'Presenca');
define('Expenses', 'Despesas');
define('Salaried', 'Assalariado');
define('Daily', 'Diariamente');
define('Hourly', 'Horario');
define('Days', 'Dias');
define('Hours', 'Horas');
define('Fix amount', 'Montante Fixo');
define('Back to pay stub', 'Retorna ao pagamento');
define('Back to calendar', 'Retorna ao calendario');
define('Adjustment', 'Ajustes');
define('Submit', 'Registra');
define('Event type', 'Tipo de evento');
define('Date', 'Data');
define('Employee', 'Funcionario');
define('Type', 'Tipo');
define('General', 'Geral');
define('Pay stub', 'Pay stub');
define('Schedules', 'Agendas');
define('Givenname', 'Nome');
define('Salary/rate', 'Salario/taxa');
define('Policy', 'Politica');
define('Bank account', 'Conta bancaria');
define('Active', 'Ativo');


define('Payable', 'Fatura');
define('Adjusted', 'Ajustado');
define('Late arrival', 'Late arrival');
define('Absent full day', 'Falta o dia todo');
define('Absence hours', 'Faltou horas');
define('Working full day', 'Trabalhando o dia Todo');
define('Working hours', 'Trabalhando horas');
define('Policies', 'Politicas');
define('Expense types', 'Tipos de despesas');
define('Deductions', 'Deducoes');
define('Amendments', 'Amendments');
define('Affect net pay', 'Afeta pagamento liquido');
define('Id', 'Id');
define('Tax', 'Taxa');
define('of', 'de');
define('Salary', 'Salario');
define('Pay account', 'Conta paga');
define('Pay accounts', 'Contas pagas');
define('Pay account groups', 'Grupo de contas pagas');
define('Users', 'Usuarios');
define('Input type', 'Tipo de Inclusao');
define('Formula', 'Formula');
define('Calculation sequence', 'Sequencia de calculo');
define('Group', 'Grupo');
define('Pay items', 'Itens pagos');
define('Attributes', 'Atributos');
define('Account', 'Conta');
define('Pay event', 'Evento pago');
define('Time accounts', 'Periodo de Contas');
define('Advanced percent', 'Percentual Avancado');
define('Interval', 'Intervalo');
define('Percent', 'Percentagem');
define('Languages', 'Linguagem');
define('Code', 'Codigo');
define('Schedule', 'Agenda');
define('Hourly account', 'Conta Horaria');
define('Daily account', 'Conta Diaria');
define('Calculate', 'Calcula');
define('Show in report', 'Mostra no relatorio');
define('Use as selector', 'Usa como seletor');
define('Add', 'Adiciona');

define('Lock current period', 'Periodo fechado');
define('Unlock last period', 'Abre ultimo periodo');
define('Payment report', 'Relatorio de pagamento');
define('Payment file', 'Arquivo de pagamento');
define('Create account', 'Cria conta');
define('Street', 'Rua');
define('Zipcode', 'CEP');
define('City', 'Cidade');
define('Daily forms', 'Formulario diario');
define('Teams', 'Grupos');
define('Team', 'Grupo');
define('Print', 'Imprime');
define('Units', 'Unidades');
define('Employees', 'Funcionarios');
define('Daily report', 'Relatorio diario');
define('End of period', 'Final do periodo');
define('Configuration', 'Configuracao');
/* Add by JBTorres - 2008 Fev,02           */



/*-----------------------------------------*/
/*           Project module                */
/*-----------------------------------------*/
/* Add by JBTorres - 2008 Fev,02           */
define('Project', 'Projeto');


/*-----------------------------------------*/
/*        General Leader module            */
/*-----------------------------------------*/
define('General ledger', 'Contabilidade');
define('Accounting', 'Contabilidade');
define('Category', 'Categoria');
define('Narrative', 'Descricao');
define('Transaction', 'Transacao');

define('History', 'Historico');
define('Accounts', 'Contas');
define('Account groups', 'Grupo de Contas');
define('Account configuration', 'Configuracao de conta');
define('Bank accounts', 'Contas bancarias');
define('Revenues', 'Receitas');
define('Assets', 'Ativos');
define('Profit', 'Ganho');
define('Liabilities', 'Passivos');
/* Add by JBTorres - 2008 Fev,02           */



/*-----------------------------------------*/
/*              Security module            */
/*-----------------------------------------*/
/* Add by JBTorres - 2008 Fev,02           */
define('Common', 'Seguranca');
define('User groups', 'Grupo de usuarios');
define('Sessions', 'Sessoes');
define('Logger', 'Lista de Erros');
define('Error', 'Erros');
define('Security', 'Seguranca');
define('Company info', 'Informacoes da Empresa');
define('Company name', 'Nome da Empresa');
define('Street address', 'Endereco');
define('Zip code', 'CEP (xxxxx-xxx)');
define('Registration no', 'No CNPJ');
define('Telephone no', 'No Telefone');
define('Remote host', 'No IP');

?>
