<?php
/*******************************************************************************
* Software: th-erp Chinese Translate                                           *
* Version:  xxxx                                                               *
* Date:     2008-10-01                                                         *
* Author:   Lear.Li                                                            *
* License:  Freeware                                                           *
*                                                                              *
* You may use, modify and redistribute this software as you wish.              *
*******************************************************************************/

define('Login', '登录');	//Login
define('Username', '用户名');	//Username
define('Password', '口令');	//Password

define('Switch module', '切换模块');	//Switch module
define('User', '用户');	//User
define('Logout', '注销');	//Logout
define('Select module', '选择模块');	//Select module
define('Sales', '销售');	//Sales
define('Stock/Inventory', '库存管理');	//Stock/Inventory
define('Manufacturing', '制造管理');	//Manufacturing
define('Payroll', '薪资管理');	//Payroll
define('Project', '项目');	//Project
define('General ledger', '总帐管理');	//General ledger
define('Common', '公共管理');	//Common

define('Customers', '客户');	//Customers
define('Period', '阶段');	//Period
define('Configuration', '配置');	//Configuration
define('Help', '帮助');	//Help
define('toolTip_newCashSalesOrder', 'toolTip_newCashSalesOrder');	//toolTip_newCashSalesOrder
define('New cash sales order', '新建现款销售单');	//New cash sales order
define('toolTip_newSalesOrder', 'toolTip_newSalesOrder');	//toolTip_newSalesOrder
define('New sales order', '新建销售单');	//New sales order
define('Point-of-sales', 'POS机');	//Point-of-sales
define('toolTip_newRecurringSalesOrder', 'toolTip_newRecurringSalesOrder');	//toolTip_newRecurringSalesOrder
define('New recurring sales order', 'New recurring sales order');	//New recurring sales order
define('toolTip_receipts', 'toolTip_receipts');	//toolTip_receipts
define('Receipts', '收款');	//Receipts
define('toolTip_showSalesOrders', 'toolTip_showSalesOrders');	//toolTip_showSalesOrders
define('Show sales orders', '销售单列表');	//Show sales orders
define('toolTip_salesAnalysis', 'toolTip_salesAnalysis');	//toolTip_salesAnalysis
define('Sales analysis', '销售单分析');	//Sales analysis


define('Current period is', '当前阶段是');	//Current period is
define('Create recurring receivables', 'Create recurring receivables');	//Create recurring receivables
define('Create time debit invoices', 'Create time debit invoices');	//Create time debit invoices

define('Cash', '现款');	//Cash
define('Card', '卡');	//Card
define('Sales order', '销售单');	//Sales order
define('Sales orders', '销售单');	//Sales orders
define('Order no', '订单号');	//Order no
define('Customer', '客户');	//Customer
define('Order date', '订单日期');	//Order date
define('Location', '仓库');	//Location
define('Receipt', '收款');	//Receipt
define('Not paid', '未支付');	//Not paid
define('Created by', '建立自');	//Created by
define('Delete', '删除');	//Delete
define('Product', '产品');	//Product
define('Comment', '注释');	//Comment
define('Quantity', '数量');	//Quantity
define('Unit price', '单价');	//Unit price
define('Purchase price', '购买价格');	//Purchase price
define('Amount', '小计');	//Amount
define('Save', '保存');	//Save
define('Search', '检索');	//Search
define('quantity_new', '新数量');	//quantity_new
define('unitprice_new', '新价格');	//unitprice_new
define('VAT', '附加税');	//VAT
define('Rounding', 'Rounding');	//Rounding
define('To pay', '需支付');	//To pay
define('Amount paid', '支付金额');	//Amount paid
define('Cancel order', '取消订单');	//Cancel order
define('Show stock moves', '显示存货调动');	//Show stock moves


define('Stock moves', '存货调动');	//Stock moves
define('Products', '产品');	//Products
define('Purchase', '购买');	//Purchase
define('Id', '标识');	//Id
define('Narrative', '描述');	//Narrative
define('Diff', '差别');	//Diff
define('Date', '日期');	//Date
define('Transaction', '事务');	//Transaction

define('Model', '型号');	//Model
define('Supplier', '供应商');	//Supplier
define('Productno', '产品号');	//Productno
define('Ordered qty, sales', '订单销售量');	//Ordered qty, sales
define('Ordered qty, purchase', '订单购买量');	//Ordered qty, purchase
define('Add product', '添加产品');	//Add product

define('Transactions', '处理');	//Transactions
define('New purchase order', '新采购单');	//New purchase order
define('Purchase orders', '采购单');	//Purchase orders
define('New payable', '新建应付');	//New payable
define('Payables', '应付');	//Payables
define('Suppliers', '供货商');	//Suppliers
define('Supplier balance', '供货商平衡');	//Supplier balance

define('Supplier name', '供货商名称');	//Supplier name
define('New', '新建');	//New

define('Create purchase order', '建立采购单');	//Create purchase order
define('Select supplier', '选择供货商');	//Select supplier
define('Leave empty for auto generated', '留空将自动生成');	//Leave empty for auto generated
define('General', '公共');	//General
define('Prices', '价格');	//Prices
define('Stock', '存储');	//Stock
define('Attributes', '属性');	//Attributes
define('Parts', '零件');	//Parts
define('Description', '描述');	//Description
define('Category', '类别');	//Category
define('Units of measure', '度量单位');	//Units of measure
define('Supplier product code', '供货商产品代码');	//Supplier product code
define('Save product', '保存产品');	//Save product


define('Categories', '类别');	//Categories
define('VAT categories', '税率类别');	//VAT categories
define('Locations', '仓库');	//Locations
define('Unit types', '度量单位');	//Unit types

define('Percent', '百分比');	//Percent
define('Name', '名称');	//Name
define('Product attributes', '产品属性');	//Product attributes


define('supplier', '供货商');	//supplier
define('Registered', '已注册');	//Registered
define('Due date', '应付截止日');	//Due date
define('Payed', '已支付');	//Payed


define('Supplier  balance', ' 供应商平衡');	//Supplier  balance
define('Balance', '平衡');	//Balance
define('Over due', 'Over due');	//Over due
define('Name:', '名称:');	//Name:

define('Id:', '标识:');	//Id:
define('Telephone type', '电话类型');	//Telephone type
define('Create', '建立');	//Create
define('Street address', '街道地址');	//Street address
define('City', '城市');	//City
define('Zip code', '邮政编码');	//Zip code
define('Country', '国家');	//Country
define('Contact', '联系方式');	//Contact
define('E-mail', '电子邮件');	//E-mail
define('Telephone numbers', '电话号码');	//Telephone numbers
define('VAT number', '纳税号');	//VAT number
define('Credit account', '赊购科目');	//Credit account
define('Credit length', '赊购有效期');	//Credit length
define('days', '天');	//days

define('Purchase order', '采购单');	//Purchase order
define('Order id', '订单标识');	//Order id
define('Payment', '支付');	//Payment
define('Received qty', 'Received qty');	//Received qty
define('Add', '添加');	//Add
define('Register payable', '登记应付');	//Register payable


define('Payable', '应付');	//Payable
define('amount', 'amount');	//amount
define('vat', '增值税');	//vat
define('duedate', 'duedate');	//duedate
define('Debit account', '借方科目');	//Debit account
define('Register', '登记');	//Register
define('Register and pay', '登记并支付');	//Register and pay

define('Add supplier', '增加供应商');	//Add supplier
define('productcode_new', '新产品码');	//productcode_new
define('Sales price', '销售价格');	//Sales price
define('salesprice_1', 'salesprice_1');	//salesprice_1
define('salesprice_2', 'salesprice_2');	//salesprice_2
define('purchaseprice_new', 'purchaseprice_new');	//purchaseprice_new
define('diff_1', 'diff_1');	//diff_1
define('diff_2', 'diff_2');	//diff_2
define('Update quantities', '更新数量');	//Update quantities
define('Create general ledger transaction for stock movement', '为移库操作建立分类帐');	//Create general ledger transaction for stock movement
define('Move', '移动');	//Move
define('pieces from', '单位 从');	//pieces from
define('to', '到');	//to
define('Re-order level', 'Re-order level');	//Re-order level
define('Re-order quantity', 'Re-order quantity');	//Re-order quantity
define('Attribute', '属性');	//Attribute
define('Option', 'Option');	//Option
define('Part', '部件');	//Part

define('Starting quantity', '开始数目');	//Starting quantity
define('Order', '订单');	//Order
define('Final quantity', '最终数目');	//Final quantity

define('Accounting', '会计科目');	//Accounting
define('History', '历史');	//History
define('Time', '时间');	//Time
define('Account', 'Account');	//Account
define('Cancel transaction', 'Cancel transaction');	//Cancel transaction
define('Years', '年');	//Years
define('Months', '月');	//Months
define('Starting', '期初值');	//Starting
define('Final', '期末值');	//Final
define('Total', '总计');	//Total
define('Profit', '利润');	//Profit

define('Interval', '周期');	//Interval
define('starttime', '开始时间');	//starttime
define('endtime', '结束时间');	//endtime
define('Print', '打印');	//Print


define('Accounts', '科目');	//Accounts
define('Account groups', '科目组');	//Account groups
define('Account configuration', '科目配置');	//Account configuration
define('Dimensions', '规模');	//Dimensions
define('Setup', '设置');	//Setup
define('Default cash', '默认现金');	//Default cash
define('Default sales', '默认销售');	//Default sales
define('Account receivable', '应收账户');	//Account receivable
define('Account payable', '应付账户');	//Account payable
define('Finished goods inventory', '制成品库存');	//Finished goods inventory
define('Raw material inventory', '源材料库存');	//Raw material inventory
define('Cost of sales', '销售成本');	//Cost of sales
define('Goods received suspense', 'Goods received suspense');	//Goods received suspense
define('VAT payable', '应付税额');	//VAT payable
define('VAT recoverable', 'VAT recoverable');	//VAT recoverable
define('Inventory adjustment', '库存调整');	//Inventory adjustment
define('Dimension', '规模');	//Dimension
define('Group', '组');	//Group
define('Accountno', '科目编码');	//Accountno
define('Load BAS accounts (Sweden)', '调入默认科目信息(瑞士)');	//Load BAS accounts (Sweden)

define('Create order', '建立订单');	//Create order
define('Select customer', '选择客户');	//Select customer
define('Customer name', '客户名称');	//Customer name
define('Customer no', '客户号');	//Customer no
define('New customer', '新客户');	//New customer
define('Recur active', 'Recur active');	//Recur active
define('Cancel order ', '取消订单 ');	//Cancel order 
define('Production orders', '产品订单');	//Production orders
define('Finished', '完成');	//Finished

define('Production order', '产品订单');	//Production order
define('Created date', '建立日期');	//Created date
define('Status', '状态');	//Status
define('Finish', '完成');	//Finish

define('Invoice from supplier ', '供货商发票 ');	//Invoice from supplier 
define('Employees', '雇员');	//Employees
define('Reporting', '报告');	//Reporting
define('End of period', 'End of period');	//End of period
define('Surname', '姓名');	//Surname
define('Show inactive', '不活跃的');	//Show inactive
define('Calendar', '日历');	//Calendar

define('Payment report', '支付报告');	//Payment report
define('Payment file', '支付文件');	//Payment file
define('Statistics', '统计');	//Statistics
define('In/Out', '入/出');	//In/Out
define('Policies', 'Policies');	//Policies
define('Pay accounts', 'Pay accounts');	//Pay accounts
define('Pay account groups', 'Pay account groups');	//Pay account groups
define('Schedules', 'Schedules');	//Schedules
define('Formulas', 'Formulas');	//Formulas
define('Teams', 'Teams');	//Teams
define('Daily forms', 'Daily forms');	//Daily forms
define('Tabs', 'Tabs');	//Tabs
define('Travel configuration', 'Travel configuration');	//Travel configuration
define('Advanced percent', 'Advanced percent');	//Advanced percent
define('Range sets', 'Range sets');	//Range sets
define('Swedish taxtables', 'Swedish taxtables');	//Swedish taxtables

define('Lock current period', 'Lock current period');	//Lock current period
define('Unlock last period', 'Unlock last period');	//Unlock last period
define('No of columns', '没有列');	//No of columns
define('Car compensation product', 'Car compensation product');	//Car compensation product
define('Advanced perccent', 'Advanced perccent');	//Advanced perccent
define('Swedish taxtable', 'Swedish taxtable');	//Swedish taxtable
define('Swedish tax tables', 'Swedish tax tables');	//Swedish tax tables
define('Table no', 'Table no');	//Table no
define('Period length', 'Period length');	//Period length
define('Filename', '文件名字');	//Filename
define('Upload', '上载');	//Upload
define('Load thai setup', '调入泰国配置');	//Load thai setup
define('Load swedish setup', '调入瑞典配置');	//Load swedish setup
define('Load demo data', '调入演示数据');	//Load demo data

define('Price lists', '价格列表');	//Price lists
define('Invoice', '发票');	//Invoice
define('Invoice configuration', '发票设置');	//Invoice configuration
define('Template', '模板');	//Template
define('Footer', '页脚');	//Footer

define('Only show', '仅显示');	//Only show
define('Not invoiced', '不开票');	//Not invoiced
define('Unpaid', '未付（不需付）');	//Unpaid
define('Overdue', '过期的');	//Overdue
define('Cancel', 'Cancel');	//Cancel
define('No', '编号');	//No
define('Invoiced', '已开票');	//Invoiced
define('Recurring', 'Recurring');	//Recurring

define('Receive goods', '接收产品');	//Receive goods
define('Show payable', '显示应付信息');	//Show payable
define('Pay', '支付');	//Pay
define('Payment payable ', '支付应付款 ');	//Payment payable 
define('Fully paid', '已完全付款');	//Fully paid
define('Show transaction', '显示会计科目');	//Show transaction

define('Payment method', '支付方法');	//Payment method
define('Price list', '价格列表');	//Price list

define('doInvoice', '开票');	//doInvoice
define('E-mail customer', '电子邮件客户');	//E-mail customer
define('Credit order', '赊购');	//Credit order

define('Address', '地址');	//Address
define('Order #', '订单号 #');	//Order #
define('Receipt date', '开票日期');	//Receipt date
define('Subtotal', '小计');	//Subtotal

define('Registrationno', '登记号');	//Registrationno

// Stock Move Order
define('Stock move order', '移库单');	//Stock move order
define('Stock move', '移库');	//Stock move
define('From Location', '来源库');	//From Location
define('To Location', '目的库');	//To Location
define('Sent', '已发送');	//Sent
define('Received', '已接收');	//Received
define('Cancelled', '已取消');	//Cancelled
define('State', '状态');	//State
define('Send goods', '发送货品');	//Send goods
define('This order is cancelled', '该订单已取消');	//This order is cancelled
define('Not Register', '未登记');	//Not Register
define('Stock Move order', '移库单');	//Stock Move order

define('Barcode', '条形码');	//Stock Move order

define('Security', '安全');	//Security
define('Languages', '语言');	//Languages
define('Company info', '公司信息');	//Company info
define('Users', '用户');	//Users
define('User groups', '用户组');	//User groups
define('Sessions', '在线信息');	//Sessions
define('Logger', '日志');	//Logger
define('Remote host', '远程主机');	//Remote host
define('Error log', '错误日志');	//Error log
define('Error', '错误');	//Error
define('Code', '代码');	//Code
define('Company name', '公司名称');	//Company name
define('Registration no', '注册号');	//Registration no
define('Telephone no', '电话号码');	//Telephone no
?>
