<?php
define('doInvoice', 'Invoice');
define('toolTip_newCashSalesOrder', 'Create a new cash sales order');
define('doInvoice', 'Invoice');
define('toolTip_newSalesOrder', 'Create a new sales order');
define('doInvoice', 'Invoice');
define('toolTip_newRecurringSalesOrder', 'Create a new recurring sales order');
define('doInvoice', 'Invoice');
define('toolTip_receipts', 'View a list of receipts given to customers');
define('doInvoice', 'Invoice');
define('toolTip_showSalesOrders', 'View a list of all sales orders');
define('doInvoice', 'Invoice');
define('toolTip_salesAnalysis', 'Display the sales analysis screen');
?>
